### ISSUE TITLE
Add support for messaging channel when a game goes on sale

### ISSUE THREAD

**Issue by snebjorn** [acdvs/isthereanydeal-lookup#39]
**Is your feature request related to a problem? Please describe.**
Missing a sale on a specific game

**Describe the solution you'd like**
Just like on isthereanydeal.com you can "watch" games and when they go below a [configurable](https://isthereanydeal.com/settings/waitlist/) price you get notified.

I'd love if the bot could watch for deals and send a message to the channel when a game goes below a price.
It would be awesome if the "goes below a price" part is just as configurable as on ITAD. But that's probably future stuff :)

**Comment by benjamin-musil** [comment]
https://github.com/acdvs/isthereanydeal-lookup/issues/24 This is already a feature thought about. Main issue is resources for this, would have to pay more on infrastructure. @acdvs has a patreon and github sponsor link on the repo frontpage https://github.com/acdvs/isthereanydeal-lookup if you'd like to pitch in :D

But yes, it is something I'd like to write

**Comment by acdvs** [comment]
Closing as duplicate.
