### ISSUE TITLE
Invite-to-server link broken

### ISSUE THREAD

**Issue by SilverlightPony** [acdvs/isthereanydeal-lookup#40]
Not a bug with the bot itself, but the "invite bot to server" link is broken; it just produces a discord web page with an error reading "Invalid OAuth2 redirect_uri".

![Authorize_access_to_your_account_-_2021-08-09_01 56 43](https://user-images.githubusercontent.com/4299310/128665154-cd878381-c6cc-40a7-ab35-2d54630c2755.png)

**Comment by acdvs** [comment]
Fixed in commit c77f10f. Thanks!
